### ISSUE TITLE
Performance: LDOM usage results in calls to conform

### ISSUE THREAD

**Issue by awkay** [fulcrologic/fulcro-garden-css#3]

**Comment by maxthoursie** [comment]
I noticed that the regular dom included generated macros, but the localized dom did not. If I include them, the calls to conform! disappears and it's just as speedy as regular dom.

**Comment by awkay** [comment]
Partially addressed in PR #4

**Comment by awkay** [comment]
I'm merging and closing.  If you decide to do any more, please open a new PR.  Thanks!

**Comment by awkay** [comment]
deployed in 3.0.7
