### ISSUE TITLE
Does not create styles unless Root component has a query

### ISSUE THREAD

**Issue by livtanong** [fulcrologic/fulcro-garden-css#5]
The snippet below will create an empty style tag.
```
(defsc Root [this props]
  {:css [[:body {:margin 0}]]}
  (dom/div
    (inj/style-element {:component Root})
    (dom/div "TODO")))
```

Relatedly, even if a query exists, changes to the root css will not take effect on hot reload. Only child components referenced via query will have updated styles on hot reload.

**Comment by awkay** [comment]
This is all documented and intended.  See docstrings.
